spring:
  application:
    name: nett-mqtt-server
server:
  port: 40003
mqtt:
  server:
    service-name: ${spring.application.name}
    port: 8002
    status-port: 8003
    heartbeat-timeout: 300
    connect-timeout: 10
    socket-type: MQTT
    center-addr: 127.0.0.1:9010
    open-count: true
    check-heartbeat: true
    open-status: true