server:
  port: 8001
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  # 忽略所有服务，只路由以下配置的服务
  host:
    connect-timeout-millis: 20000
    connection-request-timeout-millis: -1
    socket-timeout-millis: 10000
  ignored-services: '*'
  routes:
    frigate-admin:
      path: /admin/**
      service-id: frigate-admin
      strip-prefix: false
    auth-server:
      path: /oauth/**
      service-id: auth-server
      strip-prefix: false
    user-center:
      path: /user/**
      service-id: user-center
      strip-prefix: false
  sensitive-headers: '*'