server:
  port: 8001
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    frigate-admin:
      path: /admin/**
      service-id: frigate-admin
    auth-server:
      path: /oauth/**
      service-id: auth-server
  sensitive-headers: Cookie,SetCookie
security:
  oauth2:
    resource:
      jwt:
        key-value: cici
      user-info-uri: http://localhost:4001/users/current
      id: api-gateway
      prefer-token-info: false
    client:
      client-id: clientId
      client-secret: 123456
      access-token-uri: http://localhost:4001/oauth/token
      user-authorization-uri: http://localhost:4001/oauth/authorize