server:
  port: 8001

spring:
  application:
    name: resource-server
  cloud:
    gateway:
      discovery:
        locator:  # enable:true  就是gateway默认从注册中心获取服务，为每一个服务创建一个router,这个router将以服务名开头的请求路径转发到对应的服务
          enabled: false
          lower-case-service-id: true
      routes:
        - id: frigate-admin
          url: lb://frigate-admin
          predicates:
            - Path: /admin/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostAddrKeyResolver}' #用于现流的键的解析器Bean对象的名称，使用SpEl表达式根据#{@beanName}从Spring 容器中获取bean对象
                redis-rate-limiter.replenishRate: 1  #令牌桶每秒填充平均速率
                redis-rate-limiter.burstCapacity: 3  #令牌桶总容量
            - name: StripPrefix
              args:
                parts: 1
  security:
    oauth2:
      client:
        registration:
          example:
            client-id: client_id
            client-secret: client_secret
            authorization-grant-type: authorization_code
            redirect-url-template: '{baseUrl}/login/oauth2/code/{registrationId}'
            clientName: gateway
        provider:
          example:
            authorization-url: http://localhost:4001/oauth/authorize
            token-uri: http://localhost:4001/oauth/token
            jwt-key-uri: http://localhost:4001/oauth/token_key
            userNameAttribute: user_name
  redis:
    host: localhost
    port: 6379
    database: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:4001/user

