server:
  port: 4001
spring:
  application:
    name: doc-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
zuul:
  add-proxy-headers: true
  sensitive-headers: '*'
  routes:
    auth-service:
      path: /oauth/**
      serviceId: auth-service
      stripPrefix: false
    rbac-service:
      path: /rbac/**
      serviceId: rbac-service
      stripPrefix: false
  ignored-patterns: '*'
security:
  oauth2:
    client:
      client-id: client
      access-token-uri: http://localhost:4000/oauth/token
      user-authorization-uri: http://localhost:4000/oauth/authorize
      client-secret: 123456
      authentication-scheme: form
      grant-type: client_credentials
      authorized-grant-types: client_credentials
    resource:
      user-info-uri: http://localhost:4000/oauth/user/current
      prefer-token-info: false
      token-info-uri: http://localhost:4000/oauth/check_token
swagger:
  doc:
    services: rbac-service
proxy:
  auth:
    routes:
      auth-service: oauth2
      rbac-service: rbac
spring.main.allow-bean-definition-overriding: true