server:
  port: 4001
spring:
  application:
    name: doc-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
zuul:
  add-proxy-headers: true
security:
  oauth2:
    client:
      client-id: code
      user-authorization-uri: http://localhost:4000/oauth/authorize
      access-token-uri: http://localhost:4000/oauth/token
      client-secret: 123456
    resource:
      user-info-uri: http://localhost:4000/user/current
      prefer-token-info: true
swagger:
  doc:
    services: rbac-service
