server:
  port: 4002
spring:
  application:
    name: id-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.115.131.208:3306/work_node?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml