server:
  port: 4000
spring:
  application:
    name: sso-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.115.131.208:3306/oauth2?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  session:
    store-type: redis
  thymeleaf:
    suffix: .html
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    port: 6379
    database: 0
    host: localhost
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
  profiles:
    active: dev