server:
  port: 4012
spring:
  application:
    name: delay-service
  redis:
    port: 6379
    database: 0
    host: localhost
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
ribbon:
  ReadTimeout: 10000