server:
  port: 9002
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
zuul:
  # 忽略所有服务，只路由以下配置的服务
  host:
    connect-timeout-millis: 20000
    connection-request-timeout-millis: -1
    socket-timeout-millis: 10000
  ignored-services: '*'
  routes:
    frigate-admin:
      path: /admin/**
      service-id: frigate-admin
      strip-prefix: false
    auth-service:
      path: /oauth/**
      service-id: auth-service
      strip-prefix: false
    rbac-service:
      path: /rbac/**
      service-id: rbac-service
      strip-prefix: false
  sensitive-headers: '*'
security:
  oauth2:
    client:
      client-id: password
      client-secret: 123456
      oauth-token-uri: http://auth-service/oauth/login
      ignore-patterns:
        - /oauth/login
    resource:
      user-info-uri: http://auth-service/oauth/user/current
      prefer-token-info: false
      token-info-uri: http://auth-service/oauth/check_token
spring.main.allow-bean-definition-overriding: true