server:
  port: 9002
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
zuul:
  # 忽略所有服务，只路由以下配置的服务
  host:
    connect-timeout-millis: 20000
    connection-request-timeout-millis: -1
    socket-timeout-millis: 10000
  ignored-services: '*'
  routes:
    frigate-admin:
      path: /admin/**
      service-id: frigate-admin
      strip-prefix: false
    auth-service:
      path: /oauth/**
      service-id: auth-service
      strip-prefix: false
    rbac-service:
      path: /rbac/**
      service-id: rbac-service
      strip-prefix: false
  sensitive-headers: '*'