spring:
  application:
    name: sso-client-third
server:
  port: 9903
  servlet:
    context-path: /third
security:
  oauth2:
    client:
      client-id: third
      client-secret: 123456
      access-token-uri: http://localhost:4000/oauth/token
      user-authorization-uri: http://localhost:4000/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:4000/oauth/token_key
        key-value: 123456
