server:
  port: 5001
spring:
  application:
    name: rbac-service
  redis:
    host: localhost
    port: 6379
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB53Dialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
security:
  access:
    expires: 3600
    enable-refresh: true
  refresh:
    expires: 7200
swagger:
  basePackage: cn.cici.frigate.rbac
  enable: true
  title: ${spring.application.name}接口文档
  description: 测试一下
  version: 2.0.0